"""Render normalized records into browsable Markdown views."""

from __future__ import annotations

from collections import Counter, defaultdict
from datetime import UTC, datetime
from os.path import relpath
from pathlib import Path
from typing import Any, Iterable
from urllib.parse import quote

import yaml

from .layout import RepositoryLayout
from .models import KnowledgeItem, isoformat
from .storage import load_json, write_json


GENERATED_MARKER = "<!-- generated by TheAzureUpdate/automation; do not edit directly -->"
IMPACT_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "none": 4, "unknown": 5}
WEBSITE_TAGS = {
    "ai-foundry": "AI",
    "github": "GitHub",
    "quantum": "Quantum",
    "apim": "APIM",
    "aks": "AKS",
    "app-service": "App Service",
    "cosmos-db": "Cosmos DB",
    "postgresql": "PostgreSQL",
    "azure-sql": "Azure SQL",
}

# Relevance weights used to pick the lead story and order the daily post.
# Higher is more newsworthy. These are deterministic so the same evidence
# always produces the same post.
CHANGE_WEIGHT = {
    "retired": 100,
    "breaking-change": 95,
    "deprecated": 85,
    "security": 80,
    "incident": 70,
    "known-issue": 60,
    "pricing": 40,
    "region-availability": 35,
    "maintenance": 30,
    "new": 25,
    "updated": 10,
    "no-change": 0,
}
LIFECYCLE_WEIGHT = {
    "retired": 15,
    "deprecated": 12,
    "ga": 20,
    "public-preview": 12,
    "private-preview": 6,
    "in-development": 3,
    "unknown": 0,
}
IMPACT_WEIGHT = {"critical": 40, "high": 30, "medium": 15, "low": 5, "none": 0, "unknown": 0}
ACTION_CHANGE_TYPES = {"deprecated", "retired", "breaking-change", "security", "incident"}
LAUNCH_LIFECYCLES = {"ga", "public-preview", "private-preview"}


def _is_resolved_incident(item: KnowledgeItem) -> bool:
    """A closed status-page incident is history, not something to act on."""
    return item.change_type == "incident" and "resolved" in item.summary.casefold()


def _relevance_score(item: KnowledgeItem) -> int:
    """Rank an item by how much a reader needs to know about it today."""
    score = CHANGE_WEIGHT.get(item.change_type, 10)
    score += LIFECYCLE_WEIGHT.get(item.lifecycle, 0)
    score += IMPACT_WEIGHT.get(item.customer_impact, 0)
    if item.source_tier == 1:
        score += 10
    if _is_resolved_incident(item):
        score -= 75
    return score


def _score_sort_key(item: KnowledgeItem) -> tuple[int, float, str]:
    date = item.published_at or item.observed_at
    return (-_relevance_score(item), -date.timestamp(), item.title.casefold())


def _technology_label(technology: str) -> str:
    return WEBSITE_TAGS.get(technology, technology)


def _display_title(item: KnowledgeItem) -> str:
    """Drop feed prefixes that repeat the lifecycle shown beside the title."""
    title = " ".join(item.title.split())
    for tag in ("[Launched]", "[In development]", "[In preview]", "[Retirement]"):
        if title.startswith(tag):
            title = title[len(tag):].lstrip()
    for prefix in (
        "Generally Available:",
        "General Availability:",
        "Public Preview:",
        "Private Preview:",
        "Preview:",
    ):
        if title.casefold().startswith(prefix.casefold()):
            title = title[len(prefix):].lstrip()
            break
    return title or item.title


def _clean_summary(summary: str, limit: int = 320) -> str:
    """Trim feed summaries that were cut mid-sentence or run very long."""
    text = " ".join(summary.split()).strip()
    if not text:
        return ""
    text = text.rstrip("\u2026").rstrip()
    if len(text) > limit:
        window = text[:limit]
        cut = max(window.rfind(". "), window.rfind("! "), window.rfind("? "))
        text = window[: cut + 1] if cut > 80 else window.rstrip() + "..."
        return text
    if text and text[-1] not in ".!?)":
        cut = max(text.rfind(". "), text.rfind("! "), text.rfind("? "))
        if cut > 80:
            text = text[: cut + 1]
        elif not text.endswith("."):
            text = text + "..."
    return text


def _yaml_quote(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', "'")


def _table_cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def _status_line(item: KnowledgeItem) -> str:
    return f"`{item.lifecycle}` / `{item.change_type}` - {item.customer_impact.title()} impact"


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    normalized = content.rstrip() + "\n"
    if path.exists() and path.read_text(encoding="utf-8") == normalized:
        return
    path.write_text(normalized, encoding="utf-8", newline="\n")


def _front_matter(item: KnowledgeItem) -> str:
    data = item.to_dict()
    for body_field in ("summary", "why_it_matters", "recommended_action"):
        data.pop(body_field, None)
    rendered = yaml.safe_dump(data, sort_keys=False, allow_unicode=False).strip()
    return f"---\n{rendered}\n---"


def _item_markdown(item: KnowledgeItem) -> str:
    evidence = [item.source_url, *item.supporting_urls]
    evidence_lines = "\n".join(f"- [{url}]({url})" for url in dict.fromkeys(evidence))
    return f"""{GENERATED_MARKER}
{_front_matter(item)}

# {item.title}

## What Changed

{item.summary}

## Why It Matters to a CSA

{item.why_it_matters}

## Customer Impact

**{item.customer_impact.title()}**. Lifecycle: `{item.lifecycle}`. Change type: `{item.change_type}`.

## Recommended Action

{item.recommended_action}

## Evidence

{evidence_lines}

## Review

State: `{item.review_state}`. Observed: `{isoformat(item.observed_at)}`.
"""


def _item_sort_key(item: KnowledgeItem) -> tuple[int, float, str]:
    date = item.published_at or item.observed_at
    return (IMPACT_ORDER.get(item.customer_impact, 9), -date.timestamp(), item.title.casefold())


def _relative_link(item_path: Path, from_directory: Path) -> str:
    relative = Path(relpath(item_path, start=from_directory)).as_posix()
    return "/".join(quote(segment, safe="-._~") for segment in relative.split("/"))


def _digest_line(item: KnowledgeItem, item_path: Path, from_directory: Path) -> str:
    relative = _relative_link(item_path, from_directory)
    return (
        f"- **[{item.title}]({relative})** - {item.technology}; "
        f"`{item.lifecycle}` / `{item.customer_impact}`. {item.summary} "
        f"[Source]({item.source_url})"
    )


def _render_digest(
    from_directory: Path,
    as_of: datetime,
    changed_items: list[KnowledgeItem],
    item_paths: dict[str, Path],
    source_health: dict[str, Any],
) -> str:
    action_required = [
        item
        for item in changed_items
        if item.customer_impact in {"critical", "high"}
        or item.change_type in {"deprecated", "retired", "breaking-change", "security"}
    ]
    opportunities = [
        item
        for item in changed_items
        if item.lifecycle in {"ga", "public-preview", "private-preview"}
        or item.change_type in {"region-availability", "pricing"}
    ]
    architecture = [item for item in changed_items if "architecture" in item.csa_outcomes]
    learning = sorted(changed_items, key=_item_sort_key)[:2]
    failures = [state for state in source_health.values() if state.get("status") == "error"]

    def section(title: str, values: Iterable[KnowledgeItem], empty: str) -> str:
        rows = [
            _digest_line(item, item_paths[item.id], from_directory)
            for item in sorted(values, key=_item_sort_key)
        ]
        return f"## {title}\n\n" + ("\n".join(rows) if rows else empty)

    by_technology: dict[str, list[KnowledgeItem]] = defaultdict(list)
    for item in changed_items:
        by_technology[item.technology].append(item)
    technology_sections = []
    for technology, items in sorted(by_technology.items()):
        rows = "\n".join(
            _digest_line(item, item_paths[item.id], from_directory)
            for item in sorted(items, key=_item_sort_key)
        )
        technology_sections.append(f"### {technology}\n\n{rows}")

    failure_lines = [f"- `{state['name']}`: {state.get('error', 'unknown error')}" for state in failures]
    return "\n\n".join(
        [
            GENERATED_MARKER,
            f"# Technology Knowledge Digest - {as_of.date().isoformat()}",
            f"Generated at `{isoformat(as_of)}` from {len(changed_items)} items in this refresh view.",
            section("Action Required", action_required, "No new high-impact actions were detected."),
            section("Customer Conversation Opportunities", opportunities, "No new opportunity signals were detected."),
            section("Architecture Changes", architecture, "No new architecture-tagged changes were detected."),
            section("Learn Today", learning, "No new learning item was selected."),
            "## By Technology\n\n" + ("\n\n".join(technology_sections) or "No substantive changes."),
            "## Source Health\n\n" + ("\n".join(failure_lines) or "All enabled sources completed successfully."),
        ]
    )


def _render_source_health(source_health: dict[str, Any], as_of: datetime) -> str:
    rows = [
        "| Source | Status | Last content change | Items | Detail |",
        "| --- | --- | --- | ---: | --- |",
    ]
    for source_id, state in sorted(source_health.items()):
        detail = str(state.get("error") or "OK").replace("|", "\\|")
        rows.append(
            f"| {state.get('name', source_id)} | {state.get('status', 'unknown')} | "
            f"{state.get('last_content_change', 'unknown')} | {state.get('item_count', 0)} | {detail} |"
        )
    return f"""{GENERATED_MARKER}
# Source Health

As of `{isoformat(as_of)}`. A failed source retains its last known good content.

{chr(10).join(rows)}
"""


def _website_item(item: KnowledgeItem, *, with_action: bool = False) -> str:
    """Render one item for the website post.

    Only action-required items carry the "why it matters" and "next action"
    guidance; repeating it for every launch made the post read as boilerplate.
    """
    lines = [
        f"### [{_display_title(item)}]({item.source_url})",
        "",
        f"{_technology_label(item.technology)} - {_status_line(item)}",
        "",
        _clean_summary(item.summary),
    ]
    if with_action:
        lines += [
            "",
            f"**Why it matters:** {item.why_it_matters}",
            "",
            f"**Next action:** {item.recommended_action}",
        ]
    return "\n".join(lines)


def _one_liner(item: KnowledgeItem) -> str:
    return (
        f"- **{_technology_label(item.technology)}** - "
        f"[{_display_title(item)}]({item.source_url}) (`{item.lifecycle}`)"
    )


def _at_a_glance(items: list[KnowledgeItem], limit: int = 8) -> str:
    rows = [
        "| Technology | Update | Status |",
        "| --- | --- | --- |",
    ]
    for item in items[:limit]:
        rows.append(
            f"| {_table_cell(_technology_label(item.technology))} "
            f"| [{_table_cell(_display_title(item))}]({item.source_url}) "
            f"| `{item.lifecycle}` |"
        )
    table = "\n".join(rows)
    remaining = len(items) - limit
    if remaining > 0:
        table += f"\n\n_...and {remaining} more below._"
    return table


def _post_title(as_of: datetime, lead: KnowledgeItem | None, total: int) -> str:
    date_label = as_of.strftime("%d %B %Y")
    if lead is None:
        return f"Azure Update - {date_label}"
    headline = _display_title(lead)
    if len(headline) > 70:
        headline = headline[:67].rstrip() + "..."
    others = total - 1
    suffix = f", and {others} more" if others > 0 else ""
    return f"{date_label}: {headline}{suffix}"


def _render_website_post(
    as_of: datetime,
    changed_items: list[KnowledgeItem],
    source_health: dict[str, Any],
) -> str:
    ordered = sorted(changed_items, key=_score_sort_key)

    action_required = [
        item
        for item in ordered
        if not _is_resolved_incident(item)
        and (
            item.customer_impact in {"critical", "high"}
            or item.change_type in ACTION_CHANGE_TYPES
        )
    ]
    assigned = {item.id for item in action_required}
    notable = [
        item
        for item in ordered
        if item.id not in assigned
        and (
            item.lifecycle in LAUNCH_LIFECYCLES
            or item.change_type in {"region-availability", "pricing"}
        )
    ]
    assigned.update(item.id for item in notable)
    remainder = [item for item in ordered if item.id not in assigned]

    lead = ordered[0] if ordered else None
    body_parts: list[str] = []

    if ordered:
        body_parts.append("## At a glance\n\n" + _at_a_glance(ordered))

    if lead is not None:
        body_parts.append(
            "## The one to read first\n\n"
            + _website_item(lead, with_action=lead in action_required)
        )

    follow_up = [item for item in action_required if item is not lead]
    if follow_up:
        body_parts.append(
            "## Action required\n\n"
            + "\n\n".join(_website_item(item, with_action=True) for item in follow_up)
        )

    launches = [item for item in notable if item is not lead]
    if launches:
        by_technology: dict[str, list[KnowledgeItem]] = defaultdict(list)
        for item in launches:
            by_technology[item.technology].append(item)
        sections = []
        for technology in sorted(by_technology, key=_technology_label):
            rendered = "\n\n".join(_website_item(entry) for entry in by_technology[technology])
            sections.append(f"### {_technology_label(technology)}\n\n{rendered}")
        # The per-item heading level drops one step inside this grouped section.
        grouped = "\n\n".join(sections).replace("\n### [", "\n#### [")
        body_parts.append("## New and notable\n\n" + grouped)

    rest = [item for item in remainder if item is not lead]
    if rest:
        body_parts.append(
            "## Everything else\n\n"
            "<details>\n"
            f"<summary>{len(rest)} smaller update"
            f"{'s' if len(rest) != 1 else ''} and refreshed docs</summary>\n\n"
            + "\n".join(_one_liner(item) for item in rest)
            + "\n\n</details>"
        )

    failed_sources = [
        state for state in source_health.values() if state.get("status") == "error"
    ]
    source_note = (
        "All enabled public sources completed successfully."
        if not failed_sources
        else "Some sources failed and retained their last-known-good content: "
        + ", ".join(str(state.get("name", "unknown source")) for state in failed_sources)
        + "."
    )
    body_parts.append(f"## Source health\n\n{source_note}")

    tags = ["Azure"] + sorted(
        {_technology_label(item.technology) for item in changed_items}
    )
    title = _post_title(as_of, lead, len(changed_items))
    if lead is None:
        excerpt = "No new first-party updates were published for the tracked technologies."
    else:
        excerpt = (
            f"{len(changed_items)} verified update"
            f"{'s' if len(changed_items) != 1 else ''} across "
            f"{len({item.technology for item in changed_items})} technologies, "
            f"led by {_display_title(lead)}."
        )
        if len(excerpt) > 200:
            excerpt = excerpt[:197].rstrip() + "..."
    featured = any(item.customer_impact in {"critical", "high"} for item in changed_items)

    intro = (
        f"**{len(changed_items)} source-grounded update"
        f"{'s' if len(changed_items) != 1 else ''}** observed on "
        f"**{as_of.date().isoformat()}**, ranked by how much they change your day. "
        "Lifecycle and availability move fast, so verify volatile regional, quota, "
        "health, and preview details before making commitments."
    )

    return "\n\n".join(
        [
            "\n".join(
                [
                    "---",
                    f"id: azure-update-{as_of.date().isoformat()}",
                    f'title: "{_yaml_quote(title)}"',
                    f"date: {as_of.date().isoformat()}",
                    "author: Werner Rall",
                    f"tags: [{', '.join(tags)}]",
                    f"featured: {'true' if featured else 'false'}",
                    f'excerpt: "{_yaml_quote(excerpt)}"',
                    "---",
                ]
            ),
            GENERATED_MARKER,
            intro,
            *body_parts,
            (
                "_Generated from first-party public sources and reviewed through a "
                "pull request before publication._"
            ),
        ]
    )


def _render_retirements(root: Path, items: list[KnowledgeItem], item_paths: dict[str, Path]) -> str:
    alerts_dir = RepositoryLayout(root).alerts_dir
    retirements = [item for item in items if item.content_type == "retirement"]
    rows = [
        _digest_line(item, item_paths[item.id], alerts_dir)
        for item in sorted(retirements, key=_item_sort_key)
    ]
    return f"""{GENERATED_MARKER}
# Upcoming Retirements and Deprecations

{chr(10).join(rows) if rows else 'No retirements are currently in the collected window.'}
"""


def _render_current_alerts(root: Path, items: list[KnowledgeItem], item_paths: dict[str, Path]) -> str:
    alerts_dir = RepositoryLayout(root).alerts_dir
    alerts = [
        item
        for item in items
        if item.customer_impact in {"critical", "high"}
        and item.review_state not in {"superseded", "archived"}
    ]
    rows = [
        _digest_line(item, item_paths[item.id], alerts_dir)
        for item in sorted(alerts, key=_item_sort_key)
    ]
    return f"""{GENERATED_MARKER}
# Current High-Impact Knowledge Alerts

These are knowledge signals, not a substitute for live Azure Service Health or GitHub Status.

{chr(10).join(rows) if rows else 'No current high-impact knowledge alerts.'}
"""


def render_all(
    root: Path,
    *,
    items: dict[str, KnowledgeItem],
    changed_ids: set[str],
    source_health: dict[str, Any],
    taxonomy: dict[str, dict[str, str]],
    sources: tuple[dict[str, Any], ...],
    as_of: datetime,
) -> None:
    layout = RepositoryLayout(root)
    data_dir = layout.state_dir
    old_manifest = load_json(data_dir / "manifest.json", {"items": {}})
    old_paths = {item_id: root / relative for item_id, relative in old_manifest.get("items", {}).items()}
    item_paths: dict[str, Path] = {}

    for item in items.values():
        folder = root / taxonomy[item.technology]["folder"]
        year = (item.published_at or item.observed_at).astimezone(UTC).year
        path = folder / "updates" / str(year) / f"{item.id}.md"
        _write_text(path, _item_markdown(item))
        item_paths[item.id] = path

    for removed_id in set(old_paths).difference(items):
        path = old_paths[removed_id]
        if path.exists() and GENERATED_MARKER in path.read_text(encoding="utf-8", errors="ignore")[:200]:
            path.unlink()

    for slug, technology in taxonomy.items():
        if slug == "cross-cutting":
            continue
        folder = root / technology["folder"]
        technology_items = sorted(
            [item for item in items.values() if item.technology == slug],
            key=_item_sort_key,
        )
        recent = technology_items[:20]
        latest_rows = [
            _digest_line(item, item_paths[item.id], folder / "updates") for item in recent
        ]
        _write_text(
            folder / "updates" / "latest.md",
            f"{GENERATED_MARKER}\n# Latest {technology['display_name']} Updates\n\n"
            + ("\n".join(latest_rows) if latest_rows else "No collected updates yet."),
        )

        source_rows = []
        for source in sources:
            mapped = set(source.get("category_map", {}).values())
            if source.get("technology") == slug or slug in mapped:
                location = source.get("url") or f"https://github.com/{source.get('repository')}"
                source_rows.append(f"- [{source['name']}]({location}) - Tier {source['source_tier']}; `{source['adapter']}`")
        _write_text(
            folder / "sources" / "index.md",
            f"{GENERATED_MARKER}\n# {technology['display_name']} Sources\n\n"
            + "\n".join(source_rows),
        )
        readme = folder / "README.md"
        if not readme.exists():
            _write_text(
                readme,
                f"{GENERATED_MARKER}\n# {technology['display_name']}\n\n"
                f"- [Latest generated updates](updates/latest.md)\n"
                f"- [Curated source registry](sources/index.md)\n\n"
                "Human-authored architecture, learning, and customer conversation notes can live beside these generated views.",
            )

    changed_items = [items[item_id] for item_id in changed_ids if item_id in items]
    if changed_items:
        dated = layout.daily_dir / str(as_of.year) / f"{as_of.month:02d}" / f"{as_of.date().isoformat()}.md"
        _write_text(
            dated,
            _render_digest(dated.parent, as_of, changed_items, item_paths, source_health),
        )
        _write_text(
            layout.daily_dir / "latest.md",
            _render_digest(layout.daily_dir, as_of, changed_items, item_paths, source_health),
        )
        _write_text(
            layout.daily_dir / "pr-body.md",
            f"## Daily Azure Update\n\n"
            f"- New or changed items: {len(changed_items)}\n"
            f"- High-impact items: {sum(item.customer_impact in {'critical', 'high'} for item in changed_items)}\n"
            f"- Technologies touched: {', '.join(sorted({item.technology for item in changed_items}))}\n"
            f"- Website post: `src/posts/azure-update-{as_of.date().isoformat()}/index.md`\n\n"
            "Review the website post, `automation/reports/alerts/current.md`, and "
            "`automation/reports/alerts/source-health.md` before merging.",
        )
        daily_post_items = [
            item
            for item in items.values()
            if item.observed_at.astimezone(UTC).date() == as_of.astimezone(UTC).date()
        ]
        _write_text(
            layout.website_post_path(as_of),
            _render_website_post(as_of, daily_post_items, source_health),
        )

    all_items = list(items.values())
    _write_text(layout.alerts_dir / "current.md", _render_current_alerts(root, all_items, item_paths))
    _write_text(layout.alerts_dir / "retirements.md", _render_retirements(root, all_items, item_paths))
    _write_text(layout.alerts_dir / "source-health.md", _render_source_health(source_health, as_of))

    counts = Counter(item.technology for item in all_items)
    landing_rows = [
        f"| [{config['display_name']}](../{config['folder'].replace(' ', '%20')}/README.md) | {counts.get(slug, 0)} |"
        for slug, config in taxonomy.items()
        if slug != "cross-cutting"
    ]
    _write_text(
        layout.hub_path,
        f"""{GENERATED_MARKER}
# The Azure Update Knowledge Hub

This repository combines source-grounded evidence with reviewable daily website posts.

- [Latest daily digest](reports/daily/latest.md)
- [Current high-impact alerts](reports/alerts/current.md)
- [Retirements and deprecations](reports/alerts/retirements.md)
- [Source health](reports/alerts/source-health.md)
- [Implementation plan](docs/Plan.md)
- [Automation runbook](README.md)
- [Published post source](../src/posts/)

| Technology | Collected items |
| --- | ---: |
{chr(10).join(landing_rows)}

Generated content is marked and should be changed through the source registry or automation code. Unmarked files remain human-owned.
""",
    )

    manifest = {item_id: path.relative_to(root).as_posix() for item_id, path in item_paths.items()}
    write_json(data_dir / "manifest.json", {"version": 1, "items": manifest})
